# Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [101]:
import numpy as np
##initially lets import numpy

In [102]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [103]:
print(arr)

[1 2 3 4 5]


In [104]:
type(arr)

numpy.ndarray

In [105]:
##Multinested array
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[9,8,7,5,6]
arr1=np.array([l1,l2,l3])

In [106]:
print(arr1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 8 7 5 6]]


In [107]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 5, 6]])

In [108]:
type(arr)

numpy.ndarray

In [109]:
 arr1.shape

(3, 5)

In [110]:
arr1.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 8, 7, 5, 6]])

In [111]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 8],
       [7, 5, 6]])

In [112]:
arr1.shape

(3, 5)

# Indexing

In [113]:
##acessing the arr elements
arr

array([1, 2, 3, 4, 5])

In [114]:
arr[3]

4

In [154]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 5, 6]])

In [116]:
arr1[1:,:3]

array([[2, 3, 4],
       [9, 8, 7]])

In [117]:
arr1[0:2,0:3]

array([[1, 2, 3],
       [2, 3, 4]])

In [118]:
arr

array([1, 2, 3, 4, 5])

In [119]:
#copy() function and broadcasting
arr[3:]=100
arr

array([  1,   2,   3, 100, 100])

In [121]:
arr

array([  1,   2,   3, 100, 100])

In [122]:
arr[4:]=500
arr

array([  1,   2,   3, 100, 500])

In [123]:
## Some conditions very useful in Exploratory Data Analysis

val=3
arr[arr>=3] #checking the condition

array([  3, 100, 500])

In [130]:
val=3
arr>=3

array([False,  True,  True,  True])

In [124]:
arr=np.arange(0,10)

In [125]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [127]:
arr=np.arange(0,10,step=3)
arr

array([0, 3, 6, 9])

In [128]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [129]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [133]:
arr2=np.arange(0,10).reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [134]:
arr3=np.arange(0,10).reshape(2,5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [137]:
arr4=np.arange(0,10).reshape(2,5)
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [138]:
arr4*arr3

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [141]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [143]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [144]:
## random distribution
np.random.rand(3,5)

array([[0.32510547, 0.88260961, 0.25309785, 0.35631197, 0.12054345],
       [0.13601825, 0.79719988, 0.09326434, 0.89682277, 0.81606558],
       [0.63677861, 0.77210429, 0.80102107, 0.60512211, 0.97858976]])

In [145]:
np.random.randn(4,4)

array([[-0.3670343 , -1.28104984,  0.60273504, -3.26993186],
       [ 0.7683217 ,  1.25651238,  1.15029222, -0.29073943],
       [ 0.29427678,  1.02872118,  0.18935662,  0.16236367],
       [-1.18282138, -0.67241371, -1.71548275,  0.55974269]])

In [151]:
np.random.randint(0,100,8).reshape(4,2)#change value by run the code

array([[92, 85],
       [63, 29],
       [35, 37],
       [89, 24]])

In [153]:
np.random.random_sample((1,5))

array([[0.45806134, 0.39120351, 0.49572376, 0.17086018, 0.55263185]])